<?php
/**
 * Sistemas Especializados e Innovación Tecnológica, SA de CV
 * Mpsoft.FDW - Framework de Desarrollo Web para PHP
 *
 * v.2.0.0.0 - 2016-10-12
 */
define('_FDW_VERSION', '20200721');

define("FDW_DATO_BDD_LOGICA_Y", 1);
define("FDW_DATO_BDD_LOGICA_O", 2);

define("FDW_DATO_BDD_OPERADOR_IGUAL", 1);
define("FDW_DATO_BDD_OPERADOR_MAYORQUE", 2);
define("FDW_DATO_BDD_OPERADOR_MAYOROIGUALQUE", 3);
define("FDW_DATO_BDD_OPERADOR_MENORQUE", 4);
define("FDW_DATO_BDD_OPERADOR_MENOROIGUALQUE", 5);
define("FDW_DATO_BDD_OPERADOR_DIFERENTE", 6);
define("FDW_DATO_BDD_OPERADOR_LIKE", 7);
define("FDW_DATO_BDD_OPERADOR_IN", 8);
define("FDW_DATO_BDD_OPERADOR_IGUAL_BINARIO", 9);

define("FDW_DATO_BOOL", 1);
define("FDW_DATO_CHAR", 2);
define("FDW_DATO_INT", 3);
define("FDW_DATO_FLOAT", 4);
define("FDW_DATO_DOUBLE", 5);
define("FDW_DATO_STRING", 6);
define("FDW_DATO_DATE", 7);
define("FDW_DATO_DATETIME", 8);
define("FDW_DATO_TEXT", 9);
define("FDW_DATO_TIME", 10);
define("FDW_DATO_OBJECT", 11);
define("FDW_DATO_ARRAY", 12);
define("FDW_DATO_FILE", 13);

define("FDW_DATO_PERMISO_OBTENER", 1);
define("FDW_DATO_PERMISO_AGREGAR", 2);
define("FDW_DATO_PERMISO_MODIFICAR", 4);
define("FDW_DATO_PERMISO_ELIMINAR", 8);

define("FDW_ELEMENTO_ERROR_INICIALIZAR", 1);
define("FDW_ELEMENTO_ERROR_OBTENER", 2);
define("FDW_ELEMENTO_ERROR_AGREGAR", 3);
define("FDW_ELEMENTO_ERROR_MODIFICAR", 4);
define("FDW_ELEMENTO_ERROR_ELIMINAR", 5);
define("FDW_ELEMENTO_ERROR_ELEMENTONOVALIDO", 6);
define("FDW_ELEMENTO_ERROR_ASIGNARVALOR", 7);
define("FDW_ELEMENTO_ERROR_OBTENERVALOR", 8);
